on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  TestPushPyPIDev:
    name: Test PyPi development version on ${{ matrix.runner_tag }}
    strategy:
      fail-fast: false
      matrix:
        # runner_tag: ["self-hosted"]
        runner_tag: ["ubuntu-latest"]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_pypi_test_with_lfs.yml@main
    with:
      runner_tag: ${{ matrix.runner_tag }}
      python_version: "3.13"
      optional_dependency_PyPI_tag: "[dev]"
